AWSTemplateFormatVersion: 2010-09-09

Description: RDS in stack

Resources:
  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: '{{resolve:ssm:/td2/rds/user-name:1}}'
      MasterUserPassword: '{{resolve:ssm:/td2/rds/password:1}}'

  DBUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: db-url
      Type: String
      Value: !Join [ '', [ 'jdbc:postgresql://' , !GetAtt MyRDS.Endpoint.Address, '.' , !GetAtt MyRDS.Endpoint.Port , '/' , !Ref MyRDS ] ]
