AWSTemplateFormatVersion: 2010-09-09

Description: RDS in stack

Resources:
  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 10
      MasterUsername: '{{resolve:ssm:/td2/rds/user-name}}'
      MasterUserPassword: '{{resolve:ssm:/td2/rds/password}}'


  DBEndpointAddressSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/td2/rds/' , 'db-endpoint-address' ] ]
      Type: String
      Value: !GetAtt MyRDS.Endpoint.Address

  DBEndpointPortSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/td2/rds/' , 'db-endpoint-port' ] ]
      Type: String
      Value: !GetAtt MyRDS.Endpoint.Port

  DBNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/td2/rds/' , 'db-name' ] ]
      Type: String
      Value: !Ref MyRDS

  DBUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/td2/rds/' , 'db-url' ] ]
      Type: String
      Value: !Join [ '', [ 'jdbc:postgresql://' , !GetAtt MyRDS.Endpoint.Address, '.' , !GetAtt MyRDS.Endpoint.Port , '/' , !Ref MyRDS ] ]
